apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-task
spec:
  inputs:
    params:
      - name: filename
        description: file name
        type: string
  workspaces:
    - name: kubeconfigfile
      readOnly: true
  steps:
    - name: get
      image: quay.io/openshift/origin-cli:latest
      script: |

        export KUBECONFIG="$(workspaces.kubeconfigfile.path)/$(inputs.params.filename)"
        oc get pods


