apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  params:
    - name: filename
      description: kubeconfig file name
      type: string
  workspaces:
    - name: kubeconfigFile
      readOnly: true
  steps:
    - name: get
      image: quay.io/openshift/origin-cli:latest
      script: |

        export KUBECONFIG="$(workspaces.kubeconfigFile.path)/$(inputs.params.filename)"

        #check that cluster is configured
        oc get pods


